# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-18 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(max_length=25)),
                ('obs', models.CharField(max_length=25)),
                ('data', models.DateField(auto_now_add=True)),
                ('tag', models.CharField(choices=[(1, 'Gas'), (2, 'Food')], max_length=25)),
            ],
        ),
    ]
