# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-18 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='tag',
            field=models.CharField(choices=[(1, 'Gas'), (2, 'Food'), (3, 'Fun'), (4, 'Extras'), (5, 'Contas')], max_length=25),
        ),
    ]
