# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-18 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlite', '0002_auto_20180218_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='conta',
            field=models.CharField(choices=[('1', 'Débito/Dinheiro'), ('2', 'Cartão de Crédito')], default='-', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tag',
            field=models.CharField(choices=[('1', 'Gas'), ('2', 'Food'), ('3', 'Fun'), ('4', 'Extras'), (' 5', 'Contas')], max_length=25),
        ),
    ]
