# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-18 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlite', '0004_auto_20180218_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='conta',
            field=models.CharField(choices=[('deb', 'Débito/Dinheiro'), ('cred', 'Cartão de Crédito')], max_length=25),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tag',
            field=models.CharField(choices=[('gas', 'Gas'), ('food', 'Food'), ('fun', 'Fun'), ('extras', 'Extras'), ('contas', 'Contas')], max_length=25),
        ),
    ]
